### ISSUE TITLE
`timetrace status`: Display break time without seconds

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#105]
At the moment, the break time displayed on `timetrace status` includes seconds:

```
+-------------------+----------------------+----------------+--------------+
|  CURRENT PROJECT  |  WORKED SINCE START  |  WORKED TODAY  |    BREAKS    |
+-------------------+----------------------+----------------+--------------+
| web-store         | 0h 30min             | 0h 30min       | 0h 0min 0sec |
+-------------------+----------------------+----------------+--------------+
 ```

Since timetrace doesn't deal with seconds at least from a user perspective, the output here should be `0h 0min` instead. 

There's probably a way to format this using the `Formatter` type. You can get a ready-to-use instance using `Timetrace.Formatter()`.

**Comment by dhanushsr** [comment]
Hey, I would like to contribute to this. Can you please assign this to me.

**Comment by dhanushsr** [comment]
@dominikbraun I have a doubt regarding the implementation. As I can see from the code, a common method `formatDuration` is used for format duration, which is used for all `todayTime`, `currentTime` and `breakTime`. So should this be just for break time or for all of them?

**Comment by dominikbraun** [comment]
To be honest, I'm not sure why the output is different even though the same function is being used 🤣 The output should just always be `2h 20m`, not `2h 20m 20sec` - I don't really mind about how you achieve this. You may change the output of `breakTime` or all of them if necessary.

**Comment by dhanushsr** [comment]
Sure thanks. :) The logic is if `hours` and `minutes` are zero then show `0hr 0min x seconds` else show just `hours mins` . I will just remove the use of seconds all together.
