### ISSUE TITLE
Config YAML: support per-project configurations

### ISSUE THREAD

**Issue by jrcasso** [dominikbraun/timetrace#107]
For contractors with a large number of projects, it would be nice to be able to configure per-project options.

**Comment by dominikbraun** [comment]
Thanks for this feature request! Absolutely makes sense.

---

To solve this and #108, it would probably be sufficient to create a new `config.Project` type that stores per-project configuration. Those project configurations could then be stored as a map in `config.Config` with the map key corresponding to the project key:

```go
type Config struct {
	Store      string             `json:"store"`
	Use12Hours bool               `json:"use12hours"`
	Editor     string             `json:"editor"`
	Projects   map[string]Project `json:"projects"`
}

type Project struct {
	Billable bool `json:"billable"`
}
```

This would allow the YAML configuration to look as follows:

```yaml
editor: code
projects:
  make-coffee:
    billable: false
  my-project:
    billable: true

```

Does this YAML look approachable, @jrcasso?

If I'm not missing something, this should be pretty straight-forward to implement.

**Comment by jrcasso** [comment]
@dominikbraun Yep, approach LGTM!
