### ISSUE TITLE
Config YAML: Support default billable

### ISSUE THREAD

**Issue by jrcasso** [dominikbraun/timetrace#108]
As a user, there are some projects I work on which are _always_ billable. I'd like to be able to start work on these projects without having to pass `--billable` every time I work on it.

Related issue: #107

**Comment by dominikbraun** [comment]
Hi @jrcasso, this feature is contained in [timetrace v0.13.0](https://github.com/dominikbraun/timetrace/releases/tag/v0.13.0). Per-project configurations are documented here: [Configure defaults for projects](https://github.com/dominikbraun/timetrace#configure-defaults-for-projects)
