### ISSUE TITLE
Idea: Add Starship integration/Status

### ISSUE THREAD

**Issue by sfrique** [dominikbraun/timetrace#109]
Hello folks,

I used `watson` tool from time to time, but it's python and it keeps breaking because of some dependencies from time to time.

Looking for other tools I found `timetrace`  and others like  [rtw](https://github.com/PicoJr/rtw) and [timetracking](https://github.com/hardliner66/timetracking)  

`timtrace` seems very active and I have like golang over rust, also this seems to have a better community.

So I am going to start to use `timetrace`

With all that said, I would like to see if we can add [starship](https://starship.rs/)  integration, it should be simple enough like see here: https://github.com/hardliner66/timetracking#starship and https://github.com/PicoJr/rtw#starship-prompt-integration
full doc on custom commands for starship: https://starship.rs/config/#custom-commands

I can try to implement it.

I would also like if people have Ideas on what output should we allow. 
Like, enable arbitrary format like the examples on the tools above:
`--format "{h}h {mm}m"`
`--format "{ongoing} {human_duration}"`

I think initially what it would be nice is to get the total amount worked `today` as the current status show this information already.

But at some point, I would like to be able to show only worked time for the project on that day and so on, but this may be added to the report command and not the status.

Please let me know what you guys think.

**Comment by dominikbraun** [comment]
Thanks for filing this issue! This seems to be the same requirement as #94.

**Comment by sfrique** [comment]
> Thanks for filing this issue! This seems to be the same requirement as #94.

I found that issue but forgot to add it to the description.

The purpose seems to be the same, but the implementation is different.

I can also try to add `json` as an output, but I think would be best to implement it in a separated pull request right?

**Comment by dominikbraun** [comment]
In my opinion, it would make sense to add a `--output` (short `-o` flag) that accepts `json` as a value to solve #94. This is also the way [records will be displayed as JSON/CSV](https://github.com/dominikbraun/timetrace/issues/88#issuecomment-850388905). To solve this issue, an additional `--format` flag would make sense.

**Comment by sfrique** [comment]
The basic implementation is merged: #114

**Comment by dominikbraun** [comment]
@sfrique I opened a PR that documents the Starship integration: #124 

Feel free to review it.
