### ISSUE TITLE
Project doesn't stop counting time

### ISSUE THREAD

**Issue by cmarcond** [dominikbraun/timetrace#11]
![timetrace-bug](https://user-images.githubusercontent.com/8661227/118267896-0c086100-b493-11eb-8c98-c6068dcb2154.jpg)

**Comment by cmarcond** [comment]
I delete the project and timetrace status is still displaying the project and time.

**Comment by dominikbraun** [comment]
Thanks for opening this issue! I think those status-related issues have been fixed with [v0.1.4](https://github.com/dominikbraun/timetrace/releases/tag/v0.1.4). If you're using Homebrew, run `brew upgrade timetrace` and try again.

**Comment by dominikbraun** [comment]
So this should be fixed now. Feel free to re-open the issue if it occurs again.
