### ISSUE TITLE
Packaging for Windows with Scoop

### ISSUE THREAD

**Issue by Br1ght0ne** [dominikbraun/timetrace#112]
Nice project! I went ahead and packaged it in [my Scoop bucket](https://github.com/Br1ght0ne/scoop-bucket/blob/master/timetrace.json).

To install it with Scoop:

```
scoop bucket add https://github.com/Br1ght0ne/scoop-bucket
scoop install timetrace
```

You can add that to README if you want to.

**Comment by dominikbraun** [comment]
Thanks for packaging timetrace! I'll create a PR that updates the installation instructions.
