### ISSUE TITLE
Idea: Add tags

### ISSUE THREAD

**Issue by sfrique** [dominikbraun/timetrace#115]
Is there a plan to add tags?

They are some sort of modules. but we can add multiple tags to the same project/module like `watson` does.

So we can add additional information to the task been tracked.

For instance, when I am doing dev work for a project and I want to track down more than just submodules.

`timetrace start  module1@client +dev +python`
`timetrace start module1@client +docs`
`timetrace start module2@client +dev +golang`
`timetrace start client2 +dev +golang`

This should also help with reports, lets say I want to see a report with any tag for `dev`  for instance I can also work for an open-source project and want to know how many hours of `dev` work I made that day or week whatever.

`timetrace start  timetrace@opensource +dev +golang`
`timetrace start  timetrace@opensource +docs`

I think tags give the option to add more information to the task at hand.

Maybe tags and modules have some kind of overlap

**Comment by dominikbraun** [comment]
@FelixTheodor, @rocar, @rknizzle, @aaronsheah, @joshuaherrera, @KonstantinGasser, @obnoxiousnerd, @aligator Maybe you got some suggestions for this one 😄

**Comment by KonstantinGasser** [comment]
I like the idea of it that records can have tags in addition the the project name and a project module. However I feel it would make sense to only have a max. of 2-3 tag per record and not an arbitrary amount - that way record tags would reflect the actual things done during the record (`dev` `golang`)  and modules allow to organise on a higher level. They both would not overlap then, right? 
So in general I would also appreciate having tags on the record level also regarding reports as @sfrique mentioned.

**Comment by sfrique** [comment]
So to add more information to a given record, could we also add `description` ?

Let's say you work as a salesperson, you have a bunch of sales calls to make, but making the person you calling as a `tag` maybe to overkill right? So you could add this info in a description field for a given record.

`timetrace start calls@sales +companyX -d 'Calling Jane Doe, she's the supply manager at Company X `
`timetrace start research@sales +companyX`
`timetrace start calls@sales +companyY -d 'Calling John Doe, he works at Company Y as a help desk`

So we can trackback sometime what was actually been done for some of the records. This would also be beneficial for headhunters and such.

Support for Tags is a must in my view. The description, not us much, some information could be added as tags as well.

**Comment by dominikbraun** [comment]
Descriptions for records definitively are an open ToDo. Tags are an interesting idea as well and they shouldn't be too hard to implement. I'll schedule them for timetrace v0.12.0 or v0.13.0.
