### ISSUE TITLE
`report` command: Rename `--format` flag to `--output`

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#137]
The `timetrace report` command has a flag called `--format` for specifying the output format, e. g. JSON.

However, since #114, the `timetrace status` command has a `--format` flag for specifying a custom output format and uses a flag called `--output` for specifying JSON as output format.

**How it is**

|Command|Flag|Description|
|-|-|-|
|`status`|`--output`|Output format, e.g. JSON|
|`status`|`--format`|Custom format|
|`report`|`--format`|Output format, e.g. JSON|

This should be changed: The `--format` flag of `report` should be renamed to `--output` so that it serves the same purpose as the status `--output` flag.

**How it should be**

|Command|Flag|Description|
|-|-|-|
|`status`|`--output`|Output format, e.g. JSON|
|`status`|`--format`|Custom format|
|`report`|`--output`|Output format, e.g. JSON|

Don't forget to update the documentation accordingly! 😄

**Comment by dominikbraun** [comment]
@KonstantinGasser Sorry for not making this clear when you worked on the report feature, but we had to find a name for the status `--output` flag first.

**Comment by KonstantinGasser** [comment]
Oh I see - yes makes senes to keep the logic the same way. Sure, I will change that and create a PR 😄. That also means that the `report` command does not need a `--format` flag. The `--out` flag for the output file name however can stay the same?

**Comment by dominikbraun** [comment]
> The `--out` flag for the output file name however can stay the same?

I'm afraid that an `--output` flag with a coexisting `--out` flag will be a bit confusing, but I don't know a better name 🤔

**Comment by KonstantinGasser** [comment]
how about a `--file` flag to specify the output file?

**Comment by KonstantinGasser** [comment]
@dominikbraun I opened a PR with the aligned naming convention.

**Comment by dominikbraun** [comment]
> how about a `--file` flag to specify the output file?

I also thought about `--file` or `--path`. Feel free to pick the one you prefer if you want to :-)

**Comment by dominikbraun** [comment]
Closed by #138.
