### ISSUE TITLE
Replace calculations of record durations with new `Duration` method

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#139]
There are at least two places in the code where the duration of a record (e.g. 2h if the record started at 2PM and ended at 4PM) is calculated like so:

```go
record.end.sub(record.start)
```

Those calculations should be replaced with a new `Duration` method:

```go
record.Duration()
```

The implementation of that method would just be something like this:

```go
func (r *Record) Duration() time.Duration {
    return r.end.sub(r.start)
}
```

**Comment by alksmt** [comment]
Hey, created a pull request for it including one more use case.
Along with usage of `record.end.sub(record.start)` there were cases for records being tracked at the moment, this method will handle it too now.

**Comment by dominikbraun** [comment]
Rssolved by #139.
