### ISSUE TITLE
`timetrace status` doesn't work if there was no time tracking yet

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#14]
Running `timetrace status` leads to an error if time hasn't been tracked on that day yet:

```
timetrace status
❗ Failed to obtain status: open /Users/dominik/.timetrace/records/2021-05-15: no such file or directory
```

This is because the record directory of that day, in this case `2021-05-15`, hasn't been created yet. It will be created when running `timetrace start`.

To fix this,  `Fs.EnsureDirectories` should also create a record directory for the current day:

https://github.com/dominikbraun/timetrace/blob/16b10a97b594a7e73145096e84b6fb9672048df2/fs/fs.go#L151-L166

`EnsureDirectories` is executed in advance on each `timetrace` command.

**Comment by KonstantinGasser** [comment]
Hi, cool tool - Can I have a look at the issue and create a PR?

**Comment by dominikbraun** [comment]
Of course! Just run the commands like `go run . status` locally for development.
