### ISSUE TITLE
Include project modules in reports when using the `--project` option

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#140]
Currently, project modules don't seem to be included when generating a report using `timetrace report` and specifying a `--project` filter. The logic for including modules of a project already exists for `timetrace list projects` - maybe this can be re-used.

**Comment by KonstantinGasser** [comment]
So currently `report` lists projects and their submodules as different rows in the report. I guess the idea is to have the project as parent row with all its submodules? And the filter would look like `-p grind@make-coffee` filtering for only records belonging to the `make-coffee` project and `grind` module, right? 

Also this means, that the table needs to be appended with a `module` column, right?

**Comment by KonstantinGasser** [comment]
I opened a PR for this issue.

**Comment by dominikbraun** [comment]
> So currently `report` lists projects and their submodules as different rows in the report. I guess the idea is to have the project as parent row with all its submodules? And the filter would look like `-p grind@make-coffee` filtering for only records belonging to the `make-coffee` project and `grind` module, right?
> 
> Also this means, that the table needs to be appended with a `module` column, right?

I have yet to think about this tbh, but this doesn't sound bad.

**Comment by KonstantinGasser** [comment]
In the PR I have provided some sample outputs to get a touch and feel. I think it somehow makes to provide this in the report sense since `timetrace` does support modules..

**Comment by dominikbraun** [comment]
Closed by #143.
