### ISSUE TITLE
Remove `Formatter.FormatXx` methods

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#175]
Those 3 methods should be removed:

https://github.com/dominikbraun/timetrace/blob/8a8791acf3a7acbae8f2f0fe2029f8119a96b886/core/formatter.go#L95-L111

We should call `FormatDuration` directly with the respective `Record` field instead. This removes an unnecessary abstraction.

**Comment by RedemptionC** [comment]
hello,maybe I can try this
