### ISSUE TITLE
Remove exclamation mark (`!`) from error messages

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#189]
There are some error messages that end with an exclamation mark (`An error occurred!`). However, error messages in Go shouldn't end with a `.` or `!` and have to start with a lowercase letter: `an error occurred`.

Those error messages should be corrected.

**Note:** As this is an extremely simple task, please only pick it if you want to learn how PRs work. If you're more advanced, take a look at some of the other Hacktoberfest issues.

**Comment by leandronogSS** [comment]
i would like pick up this issue
