### ISSUE TITLE
Implement `timetrace edit record` command

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#19]
Just as projects are editable via `timetrace edit project`, records should be editable using `timetrace edit record`. The command syntax should look just like the syntax of `timetrace get record`:

```
timetrace edit record [options] <YYYY-MM-DD-HH-MM>
```

* Running `edit` without any options should open the default editor to directly edit the record file (see `edit project`).
* Running `edit` _with_ options should load the record internally, apply the option values and save the record. The supported options are explained below.

**Command options**

|Flag|Short|Type|Description|Example|
|-|-|-|-|-|
|`--plus`|`-p`|String|Adds the given duration to the end time of the record.|`--add 10m`|
|`--minus`|`-m`|String|Substracts the given duration of the end time of the record.|`--minus 10m`|

Those options probably aren't too hard to implement if the durations can be parsed as `time.Duration`. In that case, calling something like `record.End.Add(plus)` should be sufficient.

**Comment by dominikbraun** [comment]
An open question would be how `--plus` operations are handled if the calculated end time lies within the timespan of another record.

**Comment by FelixTheodor** [comment]
Hello, I would like to work on this issue :)

**Comment by dominikbraun** [comment]
Resolved by #51.
