### ISSUE TITLE
Include project name in records list

### ISSUE THREAD

**Issue by rknizzle** [dominikbraun/timetrace#23]
I think the output of `timetrace list records YYYY-MM-DD` would be more useful if the project name was included in the output table

Current output of `timetrace list records YYYY-MM-DD`:
<img width="232" alt="Screen Shot 2021-05-16 at 7 59 30 PM" src="https://user-images.githubusercontent.com/40612461/118417265-47688280-b681-11eb-9517-2bb654f6995c.png">

Desired output:
<img width="349" alt="Screen Shot 2021-05-16 at 7 55 01 PM" src="https://user-images.githubusercontent.com/40612461/118417107-a11c7d00-b680-11eb-9f51-4774905cb870.png">

**Comment by dominikbraun** [comment]
This totally makes sense, thanks for filing this issue.
