### ISSUE TITLE
`timetrace stop` prints success message even if there is no tracking

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#27]
**Description:**

If there is no active time tracking, `timetrace stop` still prints a success message that tracking has been stopped.

**Steps to reproduce:**

1. Start tracking time.
2. Stop tracking time.
3. Stop tracking time again: `✔️ Stopped tracking time`

**Expected behavior:**

If there is no active time tracking, `stop` should do nothing. There should be an info (probably not an error?) message indicating that time isn't being tracked at the moment:

```
There is no active time tracking. Start tracking using `timetrace start` first.
```

**Comment by aligator** [comment]
For me this works without any problem
