### ISSUE TITLE
Remove hard-coded `"15:04"` strings

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#36]
At some places in the code base, there is the hard-coded time string `"15:04"`. This should be replaced with a `defaultTime` constant which should be used instead. Plus, if `Timetrace.Config().Use12Hours` is `true`, that default constant should be replaced with `03:04PM`.

**Comment by aaronsheah** [comment]
Hi @dominikbraun wanted to get into contributing to open source, will give this a try this week
