### ISSUE TITLE
Introduce `--revert` flag for `timetrace edit` and `timetrace delete` commands

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#38]
There should be a new `--revert` flag for `timetrace edit project`, `timetrace edit record` (once it is implemented through #19), `timetrace delete project` and `timetrace delete record`.

If the `--revert` flag is specified, the edited/deleted project/record should be restored. This means that the `edit` and `delete` commands also need to create a backup file before modifications are performed. There always should be _one_ backup file per project/record.

> Those backup files must not be taken into account by functions like `ListRecords`.

If the `--revert` flag is specified, nothing except the rollback should happen.

**Affected commands**

|Command|Flag|Action|
|-|-|-|
|`timetrace edit project`|`--revert`|Restores the backed-up project to the state before it was edited.|
|`timetrace edit record` ¹|`--revert`|Restores the backed-up record to the state before it was edited.|
|`timetrace delete project`|`--revert`|Restores the backed-up project to the state before it was deleted.|
|`timetrace delete record`|`--revert`|Restores the backed-up record to the state before it was deleted.|

¹ This command doesn't exist yet.

**Comment by aaronsheah** [comment]
Curious what you @dominikbraun envision this to be, for example: 
* how far back can I `--revert` would it just be the last action?
* if I `edit`, `delete` then `edit --revert` im guessing for this case it will not work

**Comment by dominikbraun** [comment]
* Yes, just the last action. It should roll back to the state before the previous `edit` command has been issued.
* That depends on whether the same backup file is used by `edit` and `delete`. If they use the same backup, an `edit --rollback` could indeed restore a deleted file if I'm not missing something.

**Comment by joshuaherrera** [comment]
@dominikbraun I'd like to tackle this issue if @aaronsheah is not actively working on this.

**Comment by aaronsheah** [comment]
@joshuaherrera go for it 👍
