### ISSUE TITLE
12 hour format does not differentiate between AM and PM

### ISSUE THREAD

**Issue by joshuaherrera** [dominikbraun/timetrace#55]
Hi,
In working on issue #17 in version 0.4.0, I noticed that, when 12 hour time format is configured with config.yaml, one must always pass in the PM portion of the flag, even if the time logged was in the AM, as shown.

![timetrace-time-format](https://user-images.githubusercontent.com/25521908/119086150-eb239c80-b9b9-11eb-8954-fd553c40266b.png)

It seems to me the command should allow for the user to input AM or PM, or perhaps allow the user to omit the PM entirely, with the assumption that any time entered without PM is assumed to have been logged in the AM. Thoughts?

**Comment by joshuaherrera** [comment]
Hi @dominikbraun, I'd like to take on this issue.

**Comment by joshuaherrera** [comment]
@dominikbraun After looking into it, this was user error on my part. When testing with AM time, I changed the values within the "start" and "end" keys under $HOME/.timetrace/records/2021-05-20, but I did not change the .json filename, since I did not realize the name of the file was how the records were retrieved. Apologies!

**Comment by dominikbraun** [comment]
Nevermind, #51 will implement the `timetrace edit record` command for that cases.
