### ISSUE TITLE
Include total tracked time in `timetrace list records`

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#58]
`timetrace list records` lists all records of a given date. I think it would make sense to summarize the total tracked time at the bottom of the table.

The table should look like this: https://github.com/olekukonko/tablewriter#example-2---without-border--footer--bulk-append

**Comment by obnoxiousnerd** [comment]
I haven't thought of a plan right now but I am willing to work on this.

**Comment by dominikbraun** [comment]
Hi @obnoxiousnerd! Any updates on this one? If you don't have the capacities for finishing the issue, just let me know 😄

**Comment by obnoxiousnerd** [comment]
@dominikbraun I was pretty busy recently. However, I do have some free time today, hopefully I will do it 😄
