### ISSUE TITLE
`timetrace list projects`: Display project modules

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#60]
**Regarding Proposal #53:**

The `timetrace list projects` command shall not only list projects and project modules row-by-row, e.g.:

|#|Key|
|-|-|
|1|make-coffee|
|2|grind-beans@make-coffee|
|3|brew-coffee@make-coffee|

Instead, modules should be listed as part of their respective project:

|#|Key|Modules|
|-|-|-|
|1|make-coffee|grind-beans, brew-coffee|

This should be relatively easy to implement - just create a function that loads all modules of a project and display them with the project.

**Comment by dominikbraun** [comment]
> This should be relatively easy to implement - just create a function that loads all modules of a project and display them with the project.

Note: A function `loadProjectModules` has been implemented by #61.

**Comment by FelixTheodor** [comment]
Hey, I would like to work on this :)
