### ISSUE TITLE
Update `delete project` to also remove submodules of the project

### ISSUE THREAD

**Issue by FelixTheodor** [dominikbraun/timetrace#74]
Another thing that just came to my mind regarding #72 and #53 is that `delete project` should probably also delete all submodules of the project, right? Otherwise we could again run into problems with "parentless"-modules.

**Comment by dominikbraun** [comment]
Yes, this is a remaining ToDo 👍

**Comment by jwnpoh** [comment]
Hello, may I have a go at this?

**Comment by dominikbraun** [comment]
Of course!

**Comment by dominikbraun** [comment]
Resolved by #160.
