### ISSUE TITLE
Command ```create project <key>``` is not checking for existing projects correctly

### ISSUE THREAD

**Issue by joshuaherrera** [dominikbraun/timetrace#78]
Running the ```create project <key>``` is not checking for existing projects correctly, even though there is code to handle this case. 
I'm running Manjaro Linux, in case this is an issue with how the os package interacts with linux, and I tested on timetrace 0.5.0.
![timetrace_dupes_project](https://user-images.githubusercontent.com/25521908/119441807-98a8ef80-bcdb-11eb-89dd-1455e29c9029.png)

Per the code, this would also effect the record.SaveRecord function.

**Comment by dominikbraun** [comment]
Could reproduce this issue with timetrace 0.5.0 on macOS 11.3.

**Comment by dominikbraun** [comment]
Resolved by #79.
