### ISSUE TITLE
Timetrace does not handle projects with '/' in the name

### ISSUE THREAD

**Issue by Yadasko** [dominikbraun/timetrace#8]
Hey,

I am currently working on multiple subprojects and want to use Timetrace to track my work time on these.

My initial idea was to do something like this : `parentProject/SubProject`, but it confuses Timetrace 😄 

![image](https://user-images.githubusercontent.com/1543492/118244178-8dfe8700-b49f-11eb-884e-116482b8d10f.png)

Cheers

**Comment by dominikbraun** [comment]
@Yadasko Thanks for opening this issue! The fix is contained in [timetrace v0.1.2](https://github.com/dominikbraun/timetrace/releases/tag/v0.1.2).

**Comment by Yadasko** [comment]
Sweet, thank you for the release!

**Comment by dominikbraun** [comment]
@Yadasko There was another small fix, so there even is [v0.1.3](https://github.com/dominikbraun/timetrace/releases/tag/v0.1.3) now 😅
