### ISSUE TITLE
Look for a way to auto-generate documentation for commands

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#84]
I'd love to auto-generate the documentation for commands from the `cobra.Command.Long` help text and the command's options. Maybe there's some cool way to do this?

**Comment by obnoxiousnerd** [comment]
Cobra includes command generation. Here are the docs:
https://github.com/spf13/cobra/blob/master/doc/README.md
https://github.com/spf13/cobra/blob/master/doc/md_docs.md

I will definitely play with that a bit and get back here!

**Comment by obnoxiousnerd** [comment]
I tried generating some docs, and it works:

Generated docs:

1. Index documentation
![image](https://user-images.githubusercontent.com/52596591/119674958-4215ef80-be5a-11eb-8830-ea0c8cd15123.png)

2. Document of a command
![image](https://user-images.githubusercontent.com/52596591/119675034-4e9a4800-be5a-11eb-8813-199de5f30131.png)

3. Documentation of a subcommand
![image](https://user-images.githubusercontent.com/52596591/119675204-75f11500-be5a-11eb-8e86-ec6a42feecfd.png)

Steps to generate documentation
1. Create a script file (in a separate directory)
2. Paste the `main` function from `main.go`, but with some modifications
```go
package main

import (
	"log"

	"github.com/dominikbraun/timetrace/cli"
	"github.com/dominikbraun/timetrace/config"
	"github.com/dominikbraun/timetrace/core"
	"github.com/dominikbraun/timetrace/fs"
	"github.com/dominikbraun/timetrace/out"
	"github.com/spf13/cobra/doc"
)

var version = "UNDEFINED"

func main() {
	c, err := config.FromFile()
	if err != nil {
		out.Warn("%s", err.Error())
	}

	filesystem := fs.New(c)
	timetrace := core.New(c, filesystem)

	cmd := cli.RootCommand(timetrace, version)
	err = doc.GenMarkdownTree(cmd, "./docs")
	if err != nil {
		log.Fatal(err)
	}
}
```
3. Running that script with `go run` places docs in the `docs` directory in cwd

This was the process. We can incorporate it in CI with a bit of refining. @dominikbraun Any suggestions?

**Comment by dominikbraun** [comment]
Wow, thanks! This looks exactly like what I've been looking for. I'm going to open some issues for implementing this 😄

**Comment by dominikbraun** [comment]
I'm going to close this since we found a way to auto-generate docs. The subsequent issue is #87. Thanks again for figuring this out!
