### ISSUE TITLE
Command `timetrace edit record latest` panics if the user has no records logged for today

### ISSUE THREAD

**Issue by joshuaherrera** [dominikbraun/timetrace#95]
Running `timetrace edit record latest` when a user has not logged any time today causes the program to panic, image attached. Note, I did have valid records from the day prior, so I imagine it should have grabbed the record from yesterday, but it looks like the code assumes the newest directory in ~/.timetrace/records will contain time logs.
![panic](https://user-images.githubusercontent.com/25521908/120127614-b27f8200-c174-11eb-9f40-13af52d9968b.png)

**Comment by dominikbraun** [comment]
Which timetrace version do you have? For some reason, I don't get this error:

```
timetrace edit record latest     
💡 Opening 2021-06-01 09:11:42.542106 +0200 CEST in default editor
❗ Failed to edit project: record not found
```

**Comment by joshuaherrera** [comment]
@dominikbraun I had this error on version 0.7.0. Was your records directory for 06/01 empty?

**Comment by dominikbraun** [comment]
Nevermind, I think I tried to reproduce the error the wrong way - I didn't clean up the record directory but renamed it instead.
