### ISSUE TITLE
Implement `timetrace create record` command

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#97]
Sometimes, it would make sense to directly "insert" a new record with a given time span instead of fiddling around with `timetrace edit record` on existing records.

To do so, a `timetrace create record` command is needed. I have the following syntax in mind:

```
timetrace create record <PROJECT KEY> {<YYYY-MM-DD>|today|yesterday} <HH-MM> <HH-MM>
```

**Important:** This command should check for collisions with other records, so probably all records from that date have to be loaded and checked internally.

**Comment by FelixTheodor** [comment]
I would like to work on this one! :)
